name = "ramazan05"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "46.32.187.51:443"
UUID = "0195439a-7348-76ec-b7f3-0c5160e5e1ca"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
