name = "ramazan11"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "46.32.187.51:443"
UUID = "74fedda8-427b-4e63-b368-e05415d582c2"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
